### ISSUE TITLE
На перемикач слайдера важко потрапити мишкою і пальцем на мобільному

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#29]
На перемикач слайдера важко потрапити мишкою і пальцем на мобільному. 
По суті, в перемикача є 2 активні області - прогрес-лінія і текст. Краще їх об'єднати в одну активну область. Щоб при натисканні в проміжок між лінією і текстом теж відбувалось переключення :) 

![image](https://user-images.githubusercontent.com/12620993/49683935-10b3d880-fad5-11e8-84f3-f86908b5e9e4.png)

**Comment by YuliPolishchuk** [comment]
Якщо я просто збільшу верхній падінг для тексту, воно то буде працювати, а ти приймеш?

**Comment by TanuhaUA** [comment]
так:) супер :) я не маю нічого проти паддінгів:) коли вони правильно використані:)
