### ISSUE TITLE
Блок з логотипами .logos - при ховері різкий стрибок логотипу вниз, а потім починається анімація

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#32]
![image](https://user-images.githubusercontent.com/12620993/49684021-460cf600-fad6-11e8-82a4-7ef78482051a.png)

**Comment by YuliPolishchuk** [comment]
В мене все добре, зразу починається плавна анімація! Можливо це якось від браузера залежить, я не знаю. Так вот, я вирішила просто її забрати)))))))

**Comment by TanuhaUA** [comment]
може не варто зовсім забирати? в мене, коли я ставлю .2s - тоді без ривків :) 
а стосовно браузера - я в різних пробувала...

**Comment by TanuhaUA** [comment]
ой :) це не туди :)))

**Comment by TanuhaUA** [comment]
А це сюди:
ну, в різних браузерах це проявляється.
Це тому, що при ховері img стає блоком, а до ховера він блоком не був - тому він і скаче. img потрібно зробити display: block по-дефолту, незалежно від ховера

**Comment by YuliPolishchuk** [comment]
Добре, дякую)
