### ISSUE TITLE
В футері елементи Блогу blogs__item повинні бути посиланнями

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#33]
Так само в блоці Our Stories LATEST BLOG має бути можливість перейти по посиланню на відповідну статтю блогу.

![image](https://user-images.githubusercontent.com/12620993/49684033-72c10d80-fad6-11e8-8236-bd5330557f79.png)

![image](https://user-images.githubusercontent.com/12620993/49684047-9edc8e80-fad6-11e8-9fbc-fe8dadb54fd7.png)

**Comment by grapefruitCompany** [comment]
обернул в ссылки, сделано.
