### ISSUE TITLE
Розмір viewort 320px - блоки з картою і футер

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#34]
При viewort 320px 

- OPEN MAP не зовсім по центру
![image](https://user-images.githubusercontent.com/12620993/49684068-0397e900-fad7-11e8-835a-34a5115c49a1.png)

- INSTAGRAM - не поміщається

![image](https://user-images.githubusercontent.com/12620993/49684092-90db3d80-fad7-11e8-98d7-901c5339fe03.png)

- MoGo - текст і форма - різні відступи зліва і справа
![image](https://user-images.githubusercontent.com/12620993/49684095-9df82c80-fad7-11e8-8052-2ef4a565e798.png)

**Comment by grapefruitCompany** [comment]
Футер и инстраграм поправил.
