### ISSUE TITLE
Модифікатор wrap--width100 без стилів

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#36]
Кілька разів на сторінці зустрічається модифікатор wrap--width100, але стилі для нього не описані:) Мабуть він там не потрібен :) 

https://github.com/YuliPolishchuk/MOGO/blob/37f761283b49984a554aec89241e675dd3e2be1a/src/index.html#L541

**Comment by grapefruitCompany** [comment]
Спасибо, по удалял.
