### ISSUE TITLE
Якщо в блоки з текстом блока service вставити багато тексту - все ламається :(

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#41]
![image](https://user-images.githubusercontent.com/12620993/49684459-e7974600-fadc-11e8-8257-0c7a0c168caa.png)

**Comment by grapefruitCompany** [comment]
Пришлось упростить адаптивности. Теперь нет 2ух столбцов, но зато все нормально отображается при увеличении текста.
