### ISSUE TITLE
&__text {   &-container - невірна вкладеність

### ISSUE THREAD

**Issue by TanuhaUA** [YuliPolishchuk/MOGO#42]
&__text {
    &-container

Так, на жаль, писати не можна :( 
what-we-do__text-container - це один елемент. А елементу __text в нас немає.
Вкладеність можна використовувати для повної назви елементу або для модифікаторів. 
Те, що в нас класи елементів починають з одного слова - це просто співпадіння і мають бути незалежні правила для 
&__text-container i &__text-visible

https://github.com/YuliPolishchuk/MOGO/blob/37f761283b49984a554aec89241e675dd3e2be1a/src/scss/_what-we-do.scss#L82

**Comment by vladgalafm** [comment]
Но ведь элемент __text у меня есть. Просто он вложен в __text-visible

**Comment by TanuhaUA** [comment]
(я значить не знайшла __text)
Те, що він вложений - це одна справа. Але по BEMу, назви класів елементів не мають залежати від назв класів інших елементів.
Назва класу елементу залежить лише від назви класу блоку.
